// recipes-data.js
// Complete, detailed 20-recipe dataset for FlavorShare.

window.RECIPES = [
  {
    id: 1,
    title: "Creamy Chicken Alfredo",
    author: "Gianna Rossi",
    img: "https://images.pexels.com/photos/1435895/pexels-photo-1435895.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.8,
    time: "30 min",
    calories: 720,
    servings: 2,
    tags: ["Italian", "Pasta"],
    difficulty: "Medium",
    likes: 350,
    comments: 51,
    inProgress: true,
    description:
      "A rich and velvety chicken alfredo pasta made with parmesan, butter, and heavy cream. Perfect comfort food after a long day.",
    ingredients: [
      "200g fettuccine pasta",
      "1 chicken breast, sliced",
      "1 cup heavy cream",
      "1/2 cup parmesan cheese",
      "2 tbsp butter",
      "2 garlic cloves, minced",
      "Salt and pepper",
      "Parsley for garnish",
    ],
    steps: [
      "Cook fettuccine in salted water until al dente.",
      "Season and sauté chicken until golden.",
      "Melt butter in a pan and sauté garlic.",
      "Add cream and simmer until thickened.",
      "Stir in parmesan until melted.",
      "Combine pasta, chicken, and sauce.",
      "Top with parsley and serve warm.",
    ],
  },

  {
    id: 2,
    title: "Spicy Korean Bibimbap",
    author: "Minji Park",
    img: "https://images.pexels.com/photos/811832/pexels-photo-811832.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.9,
    time: "40 min",
    calories: 540,
    servings: 2,
    tags: ["Korean", "Rice Bowl"],
    difficulty: "Medium",
    likes: 480,
    comments: 88,
    inProgress: false,
    description:
      "A colorful Korean rice bowl topped with seasoned vegetables, bulgogi beef, fried egg, and spicy gochujang sauce.",
    ingredients: [
      "2 cups cooked rice",
      "200g bulgogi beef",
      "1 carrot, julienned",
      "1 zucchini, sliced",
      "1 cup spinach",
      "1 egg",
      "2 tbsp gochujang",
      "1 tbsp sesame oil",
      "Sesame seeds",
      "Salt and pepper",
    ],
    steps: [
      "Sauté carrots, zucchini, and spinach separately.",
      "Cook bulgogi beef until caramelized.",
      "Fry an egg sunny-side-up.",
      "Assemble rice in a bowl and arrange toppings.",
      "Add gochujang and sesame oil.",
      "Garnish with sesame seeds and serve.",
    ],
  },

  {
    id: 3,
    title: "Garlic Butter Shrimp",
    author: "Olivia Cruz",
    img: "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.7,
    time: "15 min",
    calories: 390,
    servings: 2,
    tags: ["Seafood", "Quick"],
    difficulty: "Easy",
    likes: 270,
    comments: 34,
    inProgress: true,
    description:
      "Juicy shrimp tossed in garlic butter and lemon, served with rice or pasta. Quick, simple, and irresistibly flavorful.",
    ingredients: [
      "300g shrimp, peeled",
      "3 tbsp butter",
      "4 garlic cloves, minced",
      "1 tbsp lemon juice",
      "1 tsp paprika",
      "Parsley",
      "Salt and pepper",
    ],
    steps: [
      "Season shrimp with salt, pepper, and paprika.",
      "Melt butter and sauté garlic until fragrant.",
      "Add shrimp and cook 2–3 minutes.",
      "Splash with lemon juice.",
      "Garnish with parsley and serve.",
    ],
  },

  {
    id: 4,
    title: "Japanese Tonkotsu Ramen",
    author: "Haruto Sato",
    img: "https://images.pexels.com/photos/884600/pexels-photo-884600.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.9,
    time: "1 hr 20 min",
    calories: 680,
    servings: 2,
    tags: ["Japanese", "Noodles"],
    difficulty: "Hard",
    likes: 590,
    comments: 73,
    inProgress: false,
    description:
      "Authentic tonkotsu ramen with slow-simmered broth, chashu pork, soft-boiled egg, and fresh noodles.",
    ingredients: [
      "2 servings ramen noodles",
      "3 cups pork broth",
      "Chashu pork slices",
      "1 egg, soft boiled",
      "Green onions",
      "Corn kernels",
      "Nori sheet",
      "Soy sauce",
    ],
    steps: [
      "Simmer broth for at least 1 hour.",
      "Prepare soft-boiled eggs.",
      "Cook noodles to desired firmness.",
      "Assemble noodles, broth, and toppings.",
      "Serve hot with soy sauce to taste.",
    ],
  },

  {
    id: 5,
    title: "Homestyle Beef Stew",
    author: "Jack Miller",
    img: "https://images.pexels.com/photos/7699693/pexels-photo-7699693.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.6,
    time: "1 hr",
    calories: 510,
    servings: 3,
    tags: ["Stew", "Comfort Food"],
    difficulty: "Medium",
    likes: 310,
    comments: 41,
    inProgress: false,
    description:
      "A warm and savory beef stew slow-cooked with potatoes, carrots, and herbs for a rich, hearty flavor.",
    ingredients: [
      "400g beef chunks",
      "2 potatoes, diced",
      "2 carrots, chopped",
      "1 onion, chopped",
      "2 cups beef broth",
      "2 garlic cloves",
      "Rosemary",
      "Salt and pepper",
    ],
    steps: [
      "Brown beef in a pot.",
      "Add garlic and onions and sauté.",
      "Pour broth and simmer 45 minutes.",
      "Add carrots and potatoes.",
      "Cook until vegetables are tender.",
      "Serve warm.",
    ],
  },

  {
    id: 6,
    title: "Avocado Chicken Salad",
    author: "Chloe Hart",
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.4,
    time: "18 min",
    calories: 330,
    servings: 2,
    tags: ["Healthy", "Salad"],
    difficulty: "Easy",
    likes: 190,
    comments: 25,
    inProgress: false,
    description:
      "A refreshing salad mixing shredded chicken, creamy avocado, lime juice, and fresh greens.",
    ingredients: [
      "1 cup shredded chicken",
      "1 avocado, diced",
      "1 cup lettuce",
      "1/2 cup cherry tomatoes",
      "1 tbsp olive oil",
      "Lime juice",
      "Salt and pepper",
    ],
    steps: [
      "Chop vegetables.",
      "Mix chicken and avocado.",
      "Add olive oil and lime juice.",
      "Combine with greens and serve.",
    ],
  },

  {
    id: 7,
    title: "Italian Margherita Pizza",
    author: "Luca Moretti",
    img: "https://images.pexels.com/photos/724216/pexels-photo-724216.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.8,
    time: "25 min",
    calories: 620,
    servings: 2,
    tags: ["Italian", "Pizza"],
    difficulty: "Easy",
    likes: 420,
    comments: 52,
    inProgress: true,
    description:
      "Classic Italian pizza topped with tomato sauce, fresh mozzarella, and basil leaves.",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Mozzarella cheese",
      "Fresh basil",
      "Olive oil",
      "Salt",
    ],
    steps: [
      "Roll out pizza dough.",
      "Spread tomato sauce.",
      "Add mozzarella.",
      "Bake until golden.",
      "Top with basil and olive oil.",
    ],
  },

  {
    id: 8,
    title: "Thai Mango Sticky Rice",
    author: "Pailin Siriwat",
    img: "https://images.pexels.com/photos/1291712/pexels-photo-1291712.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.7,
    time: "35 min",
    calories: 450,
    servings: 3,
    tags: ["Thai", "Dessert"],
    difficulty: "Easy",
    likes: 230,
    comments: 28,
    inProgress: false,
    description:
      "A sweet Thai dessert made with sticky rice, ripe mango slices, and coconut cream.",
    ingredients: [
      "1 cup glutinous rice",
      "1 ripe mango",
      "1 cup coconut milk",
      "3 tbsp sugar",
      "Salt",
      "Sesame seeds",
    ],
    steps: [
      "Cook sticky rice.",
      "Simmer coconut milk with sugar.",
      "Combine rice and coconut sauce.",
      "Slice mango and serve together.",
    ],
  },

  {
    id: 9,
    title: "Moroccan Chicken Tagine",
    author: "Sofia Nasser",
    img: "https://images.pexels.com/photos/5908166/pexels-photo-5908166.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.9,
    time: "50 min",
    calories: 540,
    servings: 2,
    tags: ["Moroccan", "Spiced"],
    difficulty: "Hard",
    likes: 380,
    comments: 47,
    inProgress: false,
    description:
      "A flavorful spiced chicken stew simmered with apricots, almonds, and aromatic spices.",
    ingredients: [
      "2 chicken thighs",
      "1 onion",
      "1/2 cup dried apricots",
      "Almonds",
      "Cinnamon",
      "Turmeric",
      "Chicken broth",
      "Olive oil",
    ],
    steps: [
      "Brown chicken.",
      "Add onions and spices.",
      "Pour broth and simmer.",
      "Add apricots and almonds.",
      "Cook until sauce thickens.",
    ],
  },

  {
    id: 10,
    title: "Classic Pancakes",
    author: "Emma Baker",
    img: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.5,
    time: "20 min",
    calories: 380,
    servings: 4,
    tags: ["Breakfast", "Quick"],
    difficulty: "Easy",
    likes: 200,
    comments: 19,
    inProgress: false,
    description: "Fluffy homemade pancakes perfect for any breakfast table.",
    ingredients: [
      "1 cup flour",
      "1 tbsp sugar",
      "1 egg",
      "1 cup milk",
      "2 tbsp butter",
      "Salt",
    ],
    steps: [
      "Mix dry ingredients.",
      "Add wet ingredients.",
      "Heat skillet.",
      "Pour batter and flip.",
      "Serve with syrup.",
    ],
  },

  {
    id: 11,
    title: "Mexican Chicken Quesadillas",
    author: "Carlos Rivera",
    img: "https://images.pexels.com/photos/4611987/pexels-photo-4611987.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.6,
    time: "18 min",
    calories: 420,
    servings: 2,
    tags: ["Mexican", "Quick"],
    difficulty: "Easy",
    likes: 290,
    comments: 22,
    inProgress: true,
    description:
      "Crispy quesadillas filled with tender chicken, melted cheese, and peppers.",
    ingredients: [
      "Tortillas",
      "Shredded chicken",
      "Cheddar cheese",
      "Bell peppers",
      "Olive oil",
      "Salt",
    ],
    steps: [
      "Heat tortillas.",
      "Add filling.",
      "Fold and cook.",
      "Slice and serve.",
    ],
  },

  {
    id: 12,
    title: "Vegan Buddha Bowl",
    author: "Sara Mint",
    img: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.4,
    time: "25 min",
    calories: 310,
    servings: 1,
    tags: ["Vegan", "Healthy"],
    difficulty: "Easy",
    likes: 150,
    comments: 17,
    inProgress: false,
    description:
      "A nutrient-packed bowl of quinoa, chickpeas, fresh veggies, and tahini dressing.",
    ingredients: [
      "1 cup quinoa",
      "1/2 cup chickpeas",
      "Spinach",
      "Carrots",
      "Cucumber",
      "Tahini dressing",
    ],
    steps: [
      "Cook quinoa.",
      "Prepare vegetables.",
      "Assemble bowl.",
      "Drizzle dressing and serve.",
    ],
  },

  {
    id: 13,
    title: "Crispy Fried Chicken",
    author: "John Carter",
    img: "https://images.pexels.com/photos/8846005/pexels-photo-8846005.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.7,
    time: "45 min",
    calories: 820,
    servings: 3,
    tags: ["American", "Fried"],
    difficulty: "Medium",
    likes: 450,
    comments: 53,
    inProgress: false,
    description:
      "Golden, crispy fried chicken seasoned with a blend of spices for maximum flavor.",
    ingredients: [
      "6 chicken drumsticks",
      "Flour",
      "Buttermilk",
      "Paprika",
      "Garlic powder",
      "Salt",
      "Pepper",
      "Oil for frying",
    ],
    steps: [
      "Marinate chicken in buttermilk.",
      "Season flour.",
      "Coat chicken and fry.",
      "Drain excess oil.",
      "Serve hot.",
    ],
  },

  {
    id: 14,
    title: "Mediterranean Falafel Wrap",
    author: "Sofia Nasser",
    img: "https://images.pexels.com/photos/5908038/pexels-photo-5908038.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.5,
    time: "18 min",
    calories: 360,
    servings: 1,
    tags: ["Mediterranean", "Vegetarian"],
    difficulty: "Easy",
    likes: 210,
    comments: 16,
    inProgress: false,
    description:
      "Crispy falafel wrapped with hummus, lettuce, and tomatoes in warm pita bread.",
    ingredients: [
      "Falafel balls",
      "Pita bread",
      "Hummus",
      "Lettuce",
      "Tomatoes",
      "Onions",
    ],
    steps: [
      "Warm pita bread.",
      "Spread hummus.",
      "Add falafel and veggies.",
      "Wrap and serve.",
    ],
  },

  {
    id: 15,
    title: "Indian Butter Chicken",
    author: "Arjun Mehta",
    img: "https://images.pexels.com/photos/11178679/pexels-photo-11178679.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.9,
    time: "45 min",
    calories: 650,
    servings: 3,
    tags: ["Indian", "Curry"],
    difficulty: "Medium",
    likes: 510,
    comments: 66,
    inProgress: true,
    description:
      "Creamy and flavorful butter chicken simmered in a spiced tomato sauce.",
    ingredients: [
      "Chicken breast",
      "Tomato puree",
      "Cream",
      "Butter",
      "Garam masala",
      "Garlic",
      "Ginger",
      "Salt",
    ],
    steps: [
      "Marinate chicken.",
      "Cook tomato sauce.",
      "Add spices.",
      "Simmer chicken.",
      "Add cream and butter.",
    ],
  },

  {
    id: 16,
    title: "Sushi Roll Assortment",
    author: "Kenji Watanabe",
    img: "https://images.pexels.com/photos/3298688/pexels-photo-3298688.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.8,
    time: "60 min",
    calories: 300,
    servings: 3,
    tags: ["Japanese", "Seafood"],
    difficulty: "Hard",
    likes: 470,
    comments: 59,
    inProgress: false,
    description:
      "A mix of salmon rolls, tuna maki, and California rolls served with soy sauce and wasabi.",
    ingredients: [
      "Sushi rice",
      "Nori sheets",
      "Salmon",
      "Tuna",
      "Crab sticks",
      "Cucumber",
      "Avocado",
    ],
    steps: [
      "Cook sushi rice.",
      "Prepare fillings.",
      "Roll maki tightly.",
      "Slice evenly.",
      "Serve with soy sauce.",
    ],
  },

  {
    id: 17,
    title: "French Onion Soup",
    author: "Amélie Laurent",
    img: "https://images.pexels.com/photos/5908236/pexels-photo-5908236.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.6,
    time: "50 min",
    calories: 320,
    servings: 2,
    tags: ["French", "Soup"],
    difficulty: "Medium",
    likes: 260,
    comments: 33,
    inProgress: false,
    description:
      "A deeply caramelized onion soup topped with toasted bread and melted gruyere cheese.",
    ingredients: [
      "4 onions",
      "Beef broth",
      "Butter",
      "Thyme",
      "Gruyere cheese",
      "Baguette",
    ],
    steps: [
      "Caramelize onions slowly.",
      "Add broth and herbs.",
      "Simmer 20 minutes.",
      "Toast baguette slices.",
      "Top with cheese and broil.",
    ],
  },

  {
    id: 18,
    title: "Spanish Paella",
    author: "Isabella Fernández",
    img: "https://images.pexels.com/photos/802957/pexels-photo-802957.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.8,
    time: "55 min",
    calories: 540,
    servings: 4,
    tags: ["Spanish", "Rice"],
    difficulty: "Medium",
    likes: 410,
    comments: 44,
    inProgress: false,
    description:
      "Traditional Spanish paella with saffron rice, seafood, peppers, and chorizo.",
    ingredients: [
      "Rice",
      "Shrimp",
      "Mussels",
      "Chorizo",
      "Bell peppers",
      "Saffron",
      "Chicken broth",
    ],
    steps: [
      "Cook chorizo and peppers.",
      "Add rice and saffron.",
      "Pour broth and simmer.",
      "Add seafood and steam.",
      "Let rest before serving.",
    ],
  },

  {
    id: 19,
    title: "Greek Chicken Gyros",
    author: "Nikos Papadopoulos",
    img: "https://images.pexels.com/photos/5907644/pexels-photo-5907644.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.7,
    time: "30 min",
    calories: 430,
    servings: 2,
    tags: ["Greek", "Street Food"],
    difficulty: "Easy",
    likes: 260,
    comments: 29,
    inProgress: true,
    description:
      "Warm pita filled with marinated chicken, tzatziki, tomatoes, and onions.",
    ingredients: [
      "Chicken breast",
      "Pita bread",
      "Tzatziki",
      "Tomatoes",
      "Onions",
      "Lettuce",
    ],
    steps: [
      "Marinate chicken.",
      "Grill until tender.",
      "Warm pita.",
      "Assemble with vegetables and sauce.",
    ],
  },

  {
    id: 20,
    title: "Chocolate Lava Cake",
    author: "Hannah Lee",
    img: "https://images.pexels.com/photos/4109990/pexels-photo-4109990.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.9,
    time: "22 min",
    calories: 420,
    servings: 2,
    tags: ["Dessert", "Chocolate"],
    difficulty: "Medium",
    likes: 530,
    comments: 62,
    inProgress: false,
    description:
      "Warm, gooey lava cake with a molten chocolate center — rich, decadent, and irresistible.",
    ingredients: [
      "1/2 cup dark chocolate",
      "1/4 cup butter",
      "2 eggs",
      "1/4 cup sugar",
      "1/4 cup flour",
      "Cocoa powder",
    ],
    steps: [
      "Melt chocolate and butter.",
      "Whisk eggs and sugar.",
      "Combine wet and dry ingredients.",
      "Pour into molds.",
      "Bake until edges are firm and center is molten.",
    ],
  },
];
